import type { Metadata } from 'next'
import { gtFlexaExpanded, gtFlexaMono } from './ui/fonts'
import { Geist, Geist_Mono } from 'next/font/google'
import './ui/globals.css'
import { getMegaNav, getFooterNav } from './lib/queries'
import { Header } from './ui/header'
import { Footer } from './ui/footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const megaNavs = await getMegaNav()
  const footerNav = await getFooterNav()

  return (
    <html
      lang='en'
      className={`${gtFlexaExpanded.variable} ${gtFlexaMono.variable} antialiased`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header megaNavs={megaNavs} />
        <main>{children}</main>
        <Footer footerNav={footerNav} />
      </body>
    </html>
  )
}
